### PR TITLE
fix: adjust knife value, print victim damage

### PR DESCRIPTION
**Pull request by Rushaway**

### CODE REVIEW

**Comment by maximee-leroyy** [comment]
I was thinking about the state of this plugin and i think we should get rid of KnifeAlert + BoostAlert because of this:

We have the KnockbackRestrict plugin that already handles things related to knockback so we should just add a good detection system for weapons that have knockback (idk if we have a ZR native to check how much knockback the weapon or did)

**Comment by Rushaway** [comment]
ZR doesn't have any native for that.
Also knockback is related to each server. Weapons listed in both plugins is the weapons with the most kb per default.

**Comment by maximee-leroyy** [comment]
yes so we need to add a native to know each setting of weapons knockback and then we apply some threshold checks like if it has more than 1.5 knockback value, its considered a boosting weapon

**Comment by Rushaway** [comment]
Weapons like shootgun or awp have a kb of 1.0 and it's already heavy. That why it was made via damage value

**Comment by maximee-leroyy** [comment]
yeah but i guess we can make a function that tells how much velocity the player will get with this particular weapon + knockback setting

**Comment by Rushaway** [comment]
Accept this MR please, I don't want to merge this in KbRestrict.
People can choose to don't use KbRestrict if they don't want it.
It's different plugins with different features.

**Pull request merged**
